# Request constants
REQUEST_ERROR = 1
INVALID_UF = 2

# Settings table constants
CURRENT_UF_ID = 'CURRENT_UF_ID'
CURRENT_COUNTY_ID = 'CURRENT_COUNTY_ID'
COLOR_MAP_SIMULATION = 'COLOR_MAP_SIMULATION'
LAST_DATABASE_UPDATE = 'LAST_DATABASE_UPDATE'

# Propagation modes
URBAN = 1
SUBURBAN = 2
OPEN = 3

# Propagation models ids
COST231_HATA_MODEL = 1
HATA_MODEL = 2
FRISS_MODEL = 3
TWO_RAYS_GROUND_REFLECTION_MODEL = 4
LOG_DISTANCE_MODEL = 5
ONE_SLOPE_MODEL = 6

# Lat longs UFLA
UFLA_LAT_LONG_POSITION = (-21.226244, -44.978407)


MIN_SENSITIVITY = -150

bm_max_sensitivity = -80
bm_min_sensitivity = -180
